#!/usr/bin/env python3
"""
EasyStitch Core — extracted backend modules.
"""

from .image_prep import (
    normalise_image,
    apply_simplify_filter,
    quantize_image,
    load_image_from_path,
    run_image_prep,
)

from .utils import (
    NeedSecondCutError,
    rgb2lab,
    lab2rgb,
    safe_stem,
    mm_to_px,
    _hex_color_to_rgb,
    color_luminance,
    _neighbors8,
    _polyline_length,
    _simplify_points,
    _points_to_svg_path,
    _rotate_xy,
    _rotate_geom,
    _arc_coords_between,
    _svg_polyline,
    _svg_debug_polyline,
    _svg_debug_dot,
    _svg_debug_text,
    image_to_data_uri,
)

from .trace import (
    find_vtracer_cli,
    count_svg_paths,
    trace_prepared_png,
    parse_traced_svg_for_structure,
    build_structure_payload_from_trace,
    extract_stroke_candidates,
    stroke_preview_svg,
    connected_components_bool,
    zhang_suen_thin,
    _skeleton_segments,
    split_source_path_object,
)

__all__ = [
    "NeedSecondCutError",
    "rgb2lab",
    "lab2rgb",
    "safe_stem",
    "mm_to_px",
    "_hex_color_to_rgb",
    "color_luminance",
    "_neighbors8",
    "_polyline_length",
    "_simplify_points",
    "_points_to_svg_path",
    "_rotate_xy",
    "_rotate_geom",
    "_arc_coords_between",
    "_svg_polyline",
    "_svg_debug_polyline",
    "_svg_debug_dot",
    "_svg_debug_text",
    "image_to_data_uri",
    "normalise_image",
    "apply_simplify_filter",
    "quantize_image",
    "load_image_from_path",
    "run_image_prep",
    "find_vtracer_cli",
    "count_svg_paths",
    "trace_prepared_png",
    "parse_traced_svg_for_structure",
    "build_structure_payload_from_trace",
    "extract_stroke_candidates",
    "stroke_preview_svg",
    "connected_components_bool",
    "zhang_suen_thin",
    "_skeleton_segments",
    "split_source_path_object",
]
